// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIUWn6w3JR4fwiThFN-I97n0JcwEolNo4',
    appId: '1:297472054693:web:91fa913616a03249a4044c',
    messagingSenderId: '297472054693',
    projectId: 'signin-e9eef',
    authDomain: 'signin-e9eef.firebaseapp.com',
    databaseURL: 'https://signin-e9eef-default-rtdb.firebaseio.com',
    storageBucket: 'signin-e9eef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyxVzMaPzvGmlKKnQLW8XcqLMCmx8tbH0',
    appId: '1:297472054693:android:05d8204b19025f69a4044c',
    messagingSenderId: '297472054693',
    projectId: 'signin-e9eef',
    databaseURL: 'https://signin-e9eef-default-rtdb.firebaseio.com',
    storageBucket: 'signin-e9eef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtUitCkhC3CIfWETzS6UU5L4L55Z2Z8Nc',
    appId: '1:297472054693:ios:a42a8dcbb86a143fa4044c',
    messagingSenderId: '297472054693',
    projectId: 'signin-e9eef',
    databaseURL: 'https://signin-e9eef-default-rtdb.firebaseio.com',
    storageBucket: 'signin-e9eef.appspot.com',
    androidClientId: '297472054693-o8gdr21i3g59lu32jifsvr2o2jjfovno.apps.googleusercontent.com',
    iosClientId: '297472054693-26t5jgggediih9001viadgriub18tcsb.apps.googleusercontent.com',
    iosBundleId: 'com.kbyai.facerecog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtUitCkhC3CIfWETzS6UU5L4L55Z2Z8Nc',
    appId: '1:297472054693:ios:f970527b01a95fd4a4044c',
    messagingSenderId: '297472054693',
    projectId: 'signin-e9eef',
    databaseURL: 'https://signin-e9eef-default-rtdb.firebaseio.com',
    storageBucket: 'signin-e9eef.appspot.com',
    androidClientId: '297472054693-o8gdr21i3g59lu32jifsvr2o2jjfovno.apps.googleusercontent.com',
    iosClientId: '297472054693-2uct3ik7edikuqnbkpo8ukku1e4mq0an.apps.googleusercontent.com',
    iosBundleId: 'com.example.facerecognitionFlutter.RunnerTests',
  );
}
